//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IKindergardenService 
{
	void AddKindergarden(Kindergarden kindergarden);

	void DeleteKindergarden(Kindergarden kindergarden);

	Kindergarden GetKindergardenById(int id);

	void UpdateKindergarden(Kindergarden kindergarden);

	IEnumerable<Kindergarden> GetKindergardens(int id, string address);

}

