//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;

public class Kindergarden
{

    private ICollection<Child> _children;


    public virtual int Id
    {
        get;
        set;
    }

    public virtual string Address
    {
        get;
        set;
    }

    public virtual int Number
    {
        get;
        set;
    }

    public virtual ICollection<Child> Children
    {
        get { return _children ?? (_children = new Collection<Child>()); }
        set { _children = value; }
    }

}

