//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Kindergarden
{
	public virtual int Id
	{
		get;
		set;
	}

	public virtual string Address
	{
		get;
		set;
	}

	public virtual int Number
	{
		get;
		set;
	}

	public virtual IEnumerable<Child> Childen
	{
		get;
		set;
	}

}

